services:
  # ------------
  # DATA BASES
  # ------------
  mysql_users:
    image: mysql:8.0
    container_name: mysql_users
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USERS_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_USERS_DB}
      MYSQL_USER: ${MYSQL_USERS_USER}
      MYSQL_PASSWORD: ${MYSQL_USERS_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - users_data:/var/lib/mysql
      - ./user_service/script/script.sql:/docker-entrypoint-initdb.d/script.sql

  mysql_courses:
    image: mysql:8.0
    container_name: mysql_courses
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_COURSES_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_COURSES_DB}
      MYSQL_USER: ${MYSQL_COURSES_USER}
      MYSQL_PASSWORD: ${MYSQL_COURSES_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - courses_data:/var/lib/mysql
      - ./course_service/script/script.sql:/docker-entrypoint-initdb.d/script.sql
  
  mysql_quizzes:
    image: mysql:8.0
    container_name: mysql_quizzes
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_QUIZZES_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_QUIZZES_DB}
      MYSQL_USER: ${MYSQL_QUIZZES_USER}
      MYSQL_PASSWORD: ${MYSQL_QUIZZES_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - quizzes_data:/var/lib/mysql
      - ./quiz_service/script/script.sql:/docker-entrypoint-initdb.d/script.sql

  mongo_chats:
    image: mongo:8.2
    container_name: mongo_chats
    ports:
      - "27018:27017"
    volumes:
      - "chats_data:/data/db"

  # ---------------
  # MICROSERVICES
  # ---------------

  users_service:
    container_name: users_service
    build: ./user_service
    depends_on:
      - mysql_users
    env_file:
      - ./user_service/.env
    environment:
      DB_HOST: mysql_users
      DB_PORT: 3306
    ports:
      - "4001:3000"

  courses_service:
    container_name: courses_service
    build: ./course_service
    depends_on:
      - mysql_courses
    env_file:
      - ./course_service/.env
    environment:
      DB_HOST: mysql_courses
      DB_PORT: 3306
    ports:
      - "4002:3000"

  quizzes_service:
    container_name: quizzes_service
    build: ./quiz_service
    depends_on:
      - mysql_quizzes
    env_file:
      - ./quiz_service/.env
    environment:
      DB_HOST: mysql_quizzes
      DB_PORT: 3306
    ports:
      - "4003:3000"

  chats_service:
    container_name: chats_service
    build: ./message_service
    depends_on:
      - mongo_chats
    env_file:
      - ./message_service/.env
    ports:
      - "4004:3000"

  # -------------
  # API GATEWAY
  # -------------

  api_gateway:
    container_name: api_gateway
    build: ./MINAO-ApiGateway
    depends_on:
      - users_service
      - courses_service
      - quizzes_service
      - chats_service
    ports:
      - "8080:3001"
  
volumes:
  users_data:
  courses_data:
  quizzes_data:
  chats_data: